unstable_features = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
fn_single_line = true
overflow_delimited_expr = true
use_field_init_shorthand = true